[theme]
primaryColor = "#0078d4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f0f0"
textColor = "#333333"
font = "sans serif"

[server]
headless = true
enableCORS = false
maxUploadSize = 10
